In [5]:
from datetime import datetime
import pandas as pd

# Dicionário com dados fictícios de funcionários
dados_funcionarios = {
    'Nome': ['Ana Silva', 'Bruno Costa', 'Carla Souza', 'Diego Lima'],
    'Cargo': [
        'Analista de Dados',
        'Desenvolvedor Backend',
        'Gerente de Projetos',
        'Designer UX',
    ],
    'Idade': [28, 35, 42, 30],
    'Salário': [5500.00, 7200.00, 11000.00, 6000.00],
    'Tempo de Empresa': [3, 5, 10, 2],
}

# Criando o DataFrame
df = pd.DataFrame(dados_funcionarios)

# Exibindo o DataFrame
df

          Nome                  Cargo  Idade  Salário  Tempo de Empresa
0    Ana Silva      Analista de Dados     28   5500.0                 3
1  Bruno Costa  Desenvolvedor Backend     35   7200.0                 5
2  Carla Souza    Gerente de Projetos     42  11000.0                10
3   Diego Lima            Designer UX     30   6000.0                 2

In [6]:
# Selecionando uma coluna (retorna uma Series)
coluna_nome = df['Nome']
coluna_nome

0      Ana Silva
1    Bruno Costa
2    Carla Souza
3     Diego Lima
Name: Nome, dtype: str

In [7]:
# Selecionando duas colunas (retorna um DataFrame)
subconjunto = df[['Nome', 'Salário']]
subconjunto

          Nome  Salário
0    Ana Silva   5500.0
1  Bruno Costa   7200.0
2  Carla Souza  11000.0
3   Diego Lima   6000.0

In [8]:
# Obtendo o ano atual dinamicamente e calculando o ano de entrada
ano_atual = datetime.now().year
df['Ano de Entrada'] = ano_atual - df['Tempo de Empresa']

# Exibindo a tabela atualizada
df

,Nome,Cargo,Idade,Salário,Tempo de Empresa,Ano de Entrada
0,Ana Silva,Analista de Dados,28,5500.0,3,2023
1,Bruno Costa,Desenvolvedor Backend,35,7200.0,5,2021
2,Carla Souza,Gerente de Projetos,42,11000.0,10,2016
3,Diego Lima,Designer UX,30,6000.0,2,2024

In [9]:
# Criando uma Series a partir da coluna 'Salário' usando o 'Nome' como índice
salarios_series = pd.Series(
    data=df['Salário'].values, index=df['Nome'], name='Salário Atual'
)

salarios_series

Nome
Ana Silva       5500.0
Bruno Costa     7200.0
Carla Souza    11000.0
Diego Lima      6000.0
Name: Salário Atual, dtype: float64

In [10]:
%pip install pandas

Requirement already satisfied: pandas in /workspaces/Fundamentos/.venv-1/lib/python3.14/site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in /workspaces/Fundamentos/.venv-1/lib/python3.14/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /workspaces/Fundamentos/.venv-1/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /workspaces/Fundamentos/.venv-1/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.